### ISSUE TITLE
Asset request: safe following distance box/dots

### ISSUE THREAD

**Issue by greenmustard** [voyage/open-autonomous-safety#53]
Something to indicate that this is the safe following distance between a lead vehicle and Ego. So maybe a box or dotted lines or something.

**Comment by lukesbeard** [comment]
@greenmustard Now in the Roadway section of the library! 

![safe](https://user-images.githubusercontent.com/1010389/40078478-ab843a9c-5852-11e8-8be0-7aba6b09a312.gif)
